const home = "Home";
const explore = "Explore";
const inbox = "Inbox";
const shop = "Shop";
const searchHint = "Search in SwipeXyz";
const userName = "Jhon William";
const buttonText = "View Post";
const address = "Dhaka Bangladesh";
const follow = "Follow";
